### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by isbincApps** [cscan/vue-excel-editor#116]
hi, error importing the lib
```
import VueExcelEditor from './VueExcelEditor.vue'
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at r (C:\Users\Usuario\Documents\Vuejsapps\aisbotadminv1\node_modules\vue-server-renderer\build.dev.js:9343:16)
    at Object.vue-excel-editor (webpack:/external "vue-excel-editor":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/boot/exel.js (src/boot/exel.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../.quasar/server-entry.js (.quasar/server-entry.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.0 (server-bundle.js:2186:18)
```

**Comment by cscan** [comment]
Import it without .vue? Something like this:

```
import Vue from 'vue'
import App from './App.vue'
import VueExcelEditor from '../plugins/VueExcelEditor'

Vue.use(VueExcelEditor)

new Vue({
  render: h => h(App),
}).$mount('#app')
```

For details, please refer to the Vue documentation.
