### ISSUE TITLE
no default exports in vuedraggable and xlsx.js

### ISSUE THREAD

**Issue by danielKugler** [cscan/vue-excel-editor#136]
While changing to vite with a vue2 project we are now getting errors.

```
Uncaught SyntaxError: The requested module '/node_modules/vuedraggable/dist/vuedraggable.umd.js?v=ef55e21c' does not provide an export named 'default' (at PanelSetting.vue:2:8)
```

```
Uncaught SyntaxError: The requested module '/node_modules/xlsx/xlsx.js?v=ef55e21c' does not provide an export named 'default' (at VueExcelEditor.vue:7:8)
```

xlsx.js and vuedraggable seem to not provide default exports.
Therefor imports have to be adjusted.

Could you please change the import in **PanelSettings.vue**

from: _import draggable from 'vuedraggable'_
to: _import * as draggable from 'vuedraggable'_

AND in **VueExcelEditor.vue**

from: _import XLSX from 'xlsx'_
to: _import * as XLSX from 'xlsx'_

**Comment by cscan** [comment]
Pls hange to use vue3-excel-editor.

在 2024年2月8日週四 23:43，danielKugler ***@***.***> 寫道：

**Comment by danielKugler** [comment]
As i said, it is a **vue2** project.

**Comment by cscan** [comment]
Only vue3-excel-editor supports vite
